name: Build luci-app-adguardhome

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2

      - name: Setup OpenWrt SDK
        run: |
          mkdir -p openwrt-sdk
          wget https://downloads.openwrt.org/releases/23.05.0/targets/x86/64/openwrt-sdk-23.05.0-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz
          tar -xf openwrt-sdk-23.05.0-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz -C openwrt-sdk --strip-components=1

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev zlib1g-dev gawk git gettext libssl-dev xsltproc rsync unzip

      - name: Prepare luci-app-adguardhome
        run: |
          cp -r ./luci-app-adguardhome openwrt-sdk/package/
          cd openwrt-sdk
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Build luci-app-adguardhome
        run: |
          cd openwrt-sdk
          make menuconfig # 可选：手动配置选项
          make package/luci-app-adguardhome/compile V=s

      - name: Upload IPK artifact
        uses: actions/upload-artifact@v3
        with:
          name: luci-app-adguardhome-ipk
          path: |
            openwrt-sdk/bin/packages/*/luci-app-adguardhome_*.ipk
