name: Build IPK

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-ipk:
    runs-on: ubuntu-22.04

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up OpenWrt SDK environment
      - name: Setup OpenWrt SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev gawk gettext unzip file libssl-dev python3 git zlib1g-dev sudo quilt
          git clone https://github.com/openwrt/openwrt.git openwrt-sdk
          cd openwrt-sdk
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      # Add luci-app-adguardhome to package directory
      - name: Add luci-app-adguardhome package
        run: |
          cd openwrt-sdk/package
          ln -s $GITHUB_WORKSPACE/luci-app-adguardhome .
          cd ..

      # Configure the build
      - name: Configure build
        run: |
          cd openwrt-sdk
          make defconfig

      # Build the IPK package
      - name: Build IPK
        run: |
          cd openwrt-sdk
          make package/luci-app-adguardhome/compile V=s

      # Debug generated IPK path
      - name: Debug IPK Path
        run: |
          find openwrt-sdk/bin/packages -name "luci-app-adguardhome*.ipk"

      # Upload the built IPK artifact
      - name: Upload IPK
        uses: actions/upload-artifact@v3
        with:
          name: luci-app-adguardhome-ipk
          path: |
            openwrt-sdk/bin/packages/**/*luci-app-adguardhome*.ipk
